#!/usr/bin/env python3
"""
Cron 1-Hour Orchestrator — runs every hour to:
  1. Analyze live signal quality decay (WR, PF trend vs backtest baseline)
  2. Decide action per symbol: RETRAIN / ADJUST (threshold) / SKIP
  3. Run retrain if needed (max 2 symbols/cycle, staggered)
  4. Update Kelly sizing from live trades
  5. Send condensed report to Telegram

Decision Matrix per Symbol (3 possible actions):
  ┌─────────────────────────────────────────────────────┬────────────────────┐
  │ Condition                                            │ Action             │
  ├─────────────────────────────────────────────────────┼────────────────────┤
  │ WR < 50%  OR  PF < 1.2                               │ 🟥 RETRAIN (urgent)│
  │ WR 50-55%  OR  PF 1.2-1.5  + interval up             │ 🟡 RETRAIN (decay) │
  │ WR 55-60%  OR  PF 1.5-2.0  + interval up             │ 🟡 RETRAIN (time)  │
  │ WR ≥ 60%  AND  PF ≥ 2.0                               │ 🟢 SKIP (edge OK)  │
  │ Weekly cap exceeded (1x/symbol/week)                  │ 🟢 SKIP (capped)   │
  └─────────────────────────────────────────────────────┴────────────────────┘

This script is called by Hermes cron system, NOT by the system cron daemon.
"""
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent.parent  # = /root/projects/mimia-quant
sys.path.insert(0, str(ROOT))

import os
import json
import time
import warnings
warnings.filterwarnings('ignore')

from datetime import datetime, timedelta
import numpy as np

# ── Config ─────────────────────────────────────────────────────────
# All 20 trading pairs
SYMBOLS_20 = [
    '1000PEPEUSDT', 'AAVEUSDT', 'ADAUSDT', 'APTUSDT', 'ARBUSDT',
    'AVAXUSDT', 'BNBUSDT', 'BTCUSDT', 'DOGEUSDT', 'ENAUSDT',
    'ETHUSDT', 'FETUSDT', 'INJUSDT', 'LINKUSDT', 'NEARUSDT',
    'OPUSDT', 'SEIUSDT', 'SOLUSDT', 'SUIUSDT', 'UNIUSDT',
    'WIFUSDT', 'WLDUSDT', 'TIAUSDT'
]
# Remove duplicates: TIA is already covered by FET/TIA context
# Actually keep all — engine handles it
SYMBOLS = sorted(set(SYMBOLS_20))  # dedup just in case

DB_PATH = Path("data/live_trading.db")
STATUS_FILE = Path("data/ml_models/_retrain_status.json")
MODEL_DIR = Path("data/ml_models")
RETRAIN_SCRIPT = Path("scripts/training/auto_retrain.py")
OUTPUT_DIR = Path("data/cron_output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Per-cycle limits
MAX_RETRAIN_PER_CYCLE = 2     # at most 2 symbols per hour
RETRAIN_INTERVAL_HOURS = 72   # minimum 3 days between retrains (was 24)
MIN_INTERVAL_URGENT_HOURS = 24 # minimum 1 day even for urgent (WR < 55%)
MAX_RETRAIN_PER_WEEK = 1      # max 1x per symbol per week (was unlimited)
FULL_CYCLE_HOURS = 12         # complete full cycle over all symbols in 12 hours

# Signal quality thresholds — REALISTIC for live trading
# (Backtest WR 70% will realistically degrade to 55-60% live)
WR_GREEN = 0.60               # ✅ Edge OK: live WR >= 60%
WR_YELLOW = 0.55              # 🟡 Watch zone: WR 55-60%, stable edge
WR_RED = 0.50                 # 🔴 Force retrain: WR < 50%

PF_GREEN = 2.0                # ✅ Edge OK: live PF >= 2.0
PF_YELLOW = 1.5               # 🟡 Watch zone: PF 1.5-2.0
PF_RED = 1.2                  # 🔴 Force retrain: PF < 1.2

MIN_TRADES_FOR_STATS = 30     # minimum ALL-TIME trades before quality stats are meaningful
MIN_TRADES_CURRENT_MODEL = 20 # minimum trades from CURRENT deployed model before triggering retrain

# Backtest baselines — used as fallback when status file has no backtest data
# (BT WR ~70%, BT PF ~3.0 are typical for a good model)
WR_BACKTEST_BASELINE = 0.70    # expected backtest win rate
PF_BACKTEST_BASELINE = 3.0     # expected backtest profit factor

# Import Kelly sizer
sys.path.insert(0, str(ROOT))
from src.strategies.kelly_sizer import KellySizer


# ── Utility ──────────────────────────────────────────────────────────

def log(msg: str, level: str = "INFO"):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [{level}] {msg}")


def get_retrain_status() -> dict:
    """Load retrain status file."""
    if STATUS_FILE.exists():
        with open(STATUS_FILE) as f:
            return json.load(f)
    return {'symbols': {}, 'last_run': None, 'runs': []}


def get_live_stats_per_symbol(symbol: str, deployed_at: str = None) -> dict:
    """Get live trade stats (WR, PF, n_trades) for one symbol from DB.

    If deployed_at is provided, only count trades entered AFTER that timestamp
    (trades generated by the CURRENT deployed model, not the old one).
    """
    import sqlite3
    try:
        conn = sqlite3.connect(str(DB_PATH))
        cursor = conn.cursor()
        
        # Build WHERE clause: optionally filter by deployed_at
        where_clause = "symbol = ? AND exit_time IS NOT NULL AND pnl_net IS NOT NULL"
        params = [symbol]
        
        if deployed_at:
            try:
                # Convert ISO timestamp to ms since epoch
                dt = datetime.fromisoformat(deployed_at)
                deployed_ms = int(dt.timestamp() * 1000)
                where_clause += " AND entry_time >= ?"
                params.append(deployed_ms)
            except Exception as e:
                log(f"deployed_at parse failed for {symbol}: {deployed_at} -> {e}", "WARN")
                # Fall through — don't filter on error
        
        cursor.execute(f"""
            SELECT COUNT(*), COALESCE(SUM(CASE WHEN pnl_net > 0 THEN 1 ELSE 0 END), 0),
                   COALESCE(SUM(CASE WHEN pnl_net > 0 THEN pnl_net ELSE 0 END), 0),
                   COALESCE(SUM(CASE WHEN pnl_net < 0 THEN ABS(pnl_net) ELSE 0 END), 0)
            FROM live_trades
            WHERE {where_clause}
        """, params)
        row = cursor.fetchone()
        conn.close()
        if not row or row[0] < MIN_TRADES_CURRENT_MODEL:
            return {'n_trades': row[0] if row else 0, 'wr': 0.0, 'pf': 0.0,
                    'filtered_by_model': True}
        n, wins, win_pnl, loss_pnl = row
        wr = float(wins) / float(n) if n > 0 else 0.0
        pf = float(win_pnl) / float(loss_pnl) if loss_pnl > 0 else float('inf')
        return {'n_trades': int(n), 'wr': wr, 'pf': pf, 'filtered_by_model': True}
    except Exception as e:
        log(f"get_live_stats({symbol}) failed: {e}", "WARN")
        return {'n_trades': 0, 'wr': 0.0, 'pf': 0.0, 'filtered_by_model': False}


def analyze_signal_quality(symbol: str, status_data: dict) -> dict:
    """
    Analyze signal quality for one symbol.
    Uses trades from the CURRENT deployed model only (filtered by deployed_at).
    Returns dict with action, reason, and stats.
    """
    # Get deployment info
    entry = status_data.get(symbol, {})
    deployed_at = entry.get('deployed_at')  # ISO timestamp, None if never deployed
    last_retrained = entry.get('last_retrained')
    is_deployed = entry.get('deployed', False)
    
    # COUNTS: only trades from current model (filtered by deployed_at)
    live = get_live_stats_per_symbol(symbol, deployed_at=deployed_at if is_deployed else None)
    n_trades_current = live['n_trades']
    live_wr = live['wr']
    live_pf = live['pf']
    
    # Also get ALL-TIME trades for reference (unfiltered)
    live_all = get_live_stats_per_symbol(symbol, deployed_at=None)
    n_trades_all = live_all['n_trades']
    
    bt_wr_raw = entry.get('wr', WR_BACKTEST_BASELINE * 100)
    bt_pf = entry.get('pf', PF_BACKTEST_BASELINE)
    bt_wr = bt_wr_raw / 100.0 if bt_wr_raw > 1 else bt_wr_raw

    # Build decision context
    result = {
        'symbol': symbol,
        'n_trades': n_trades_current,
        'n_trades_all': n_trades_all,
        'live_wr': live_wr,
        'live_pf': live_pf,
        'bt_wr': bt_wr,
        'bt_pf': bt_pf,
        'last_retrained': last_retrained,
        'deployed_at': deployed_at,
        'deployed': is_deployed,
    }

    # ── CONTRAINT: Not enough trades from CURRENT deployed model → SKIP ──
    # This prevents premature retrain when a newly deployed model
    # only has a few live trades (which may not represent its true performance).
    if is_deployed and n_trades_current < MIN_TRADES_CURRENT_MODEL:
        result['action'] = 'SKIP'
        result['reason'] = f'current model: {n_trades_current}/{MIN_TRADES_CURRENT_MODEL} trades (too few to evaluate)'
        result['priority'] = 9  # lowest — never retrain from insufficient data
        return result

    # ── NEVER RETRAINED → always retrain once ──
    if not last_retrained:
        result['action'] = 'RETRAIN'
        result['reason'] = 'never retrained'
        result['priority'] = 1
        return result

    # ── Not enough ALL-TIME trades → time-based schedule only ──
    # Only reached if deployed=False (no current model filter)
    if n_trades_all < MIN_TRADES_FOR_STATS and not is_deployed:
        try:
            last_dt = datetime.fromisoformat(last_retrained)
            hours_since = (datetime.now() - last_dt).total_seconds() / 3600
            if hours_since >= RETRAIN_INTERVAL_HOURS:
                result['action'] = 'RETRAIN'
                result['reason'] = f'insufficient trades ({n_trades_all}) + {hours_since:.0f}h since last retrain'
                result['priority'] = 2
            else:
                result['action'] = 'SKIP'
                result['reason'] = f'too few trades ({n_trades_all}), next retrain in {RETRAIN_INTERVAL_HOURS-hours_since:.0f}h'
                result['priority'] = 5
        except Exception:
            result['action'] = 'RETRAIN'
            result['reason'] = 'insufficient trades, no valid last_retrained'
            result['priority'] = 2
        return result

    # ── Also not enough from current model but deployed_at is missing ──
    # (transition case: deployed=True but no deployed_at in old status)
    if is_deployed and n_trades_current < MIN_TRADES_CURRENT_MODEL and not deployed_at:
        # Can't filter — fall back to all-time data but be conservative
        pass  # continue with all-time data below

    # ── Helper: hours since last retrain ──
    def _hours_since_retrain(last_retrained_str):
        try:
            if not last_retrained_str:
                return 999999
            last_dt = datetime.fromisoformat(last_retrained_str)
            return (datetime.now() - last_dt).total_seconds() / 3600
        except Exception:
            return 999999

    hours_since = _hours_since_retrain(last_retrained)
    retrains_this_week = entry.get('retrains_this_week', 0)

    # ── Decide which stats to use ──
    test_wr = live_wr if n_trades_current >= MIN_TRADES_CURRENT_MODEL else live_all['wr']
    test_pf = live_pf if n_trades_current >= MIN_TRADES_CURRENT_MODEL else live_all['pf']
    test_nt = n_trades_current if n_trades_current >= MIN_TRADES_CURRENT_MODEL else n_trades_all

    # ── Force retrain: WR < 50% or PF < 1.2 ──
    # (model genuinely broken — urgent)
    if (test_wr < WR_RED or test_pf < PF_RED) and test_nt >= MIN_TRADES_FOR_STATS:
        if hours_since >= MIN_INTERVAL_URGENT_HOURS:
            result['action'] = 'RETRAIN'
            result['reason'] = f'urgent: WR {test_wr:.0%} PF {test_pf:.2f} ({test_nt} tr)'
            result['priority'] = 1
            return result
        else:
            result['action'] = 'SKIP'
            result['reason'] = f'urgent but cooldown ({hours_since:.0f}/{MIN_INTERVAL_URGENT_HOURS}h)'
            result['priority'] = 2
            return result

    # ── Yellow zone: WR 50-55% or PF 1.2-1.5 ──
    # (model degrading — retrain on schedule)
    if (test_wr < WR_YELLOW or test_pf < PF_YELLOW) and test_nt >= MIN_TRADES_FOR_STATS:
        if hours_since >= RETRAIN_INTERVAL_HOURS and retrains_this_week < MAX_RETRAIN_PER_WEEK:
            result['action'] = 'RETRAIN'
            result['reason'] = f'deteriorating: WR {test_wr:.0%} PF {test_pf:.2f} ({test_nt} tr, {hours_since:.0f}h)'
            result['priority'] = 3
            return result
        elif hours_since >= RETRAIN_INTERVAL_HOURS:
            result['action'] = 'SKIP'
            result['reason'] = f'deteriorating but weekly cap hit ({retrains_this_week}/{MAX_RETRAIN_PER_WEEK})'
            result['priority'] = 4
            return result
        else:
            result['action'] = 'SKIP'
            result['reason'] = f'slightly below: WR {test_wr:.0%} PF {test_pf:.2f} (next retrain in {RETRAIN_INTERVAL_HOURS-hours_since:.0f}h)'
            result['priority'] = 4
            return result

    # ── Green zone: WR >= 60% AND PF >= 2.0 ──
    if test_wr >= WR_GREEN and test_pf >= PF_GREEN:
        result['action'] = 'SKIP'
        result['reason'] = f'edge OK: WR {test_wr:.0%} PF {test_pf:.2f} ({test_nt} tr)'
        result['priority'] = 5
        return result

    # ── Stable edge zone: WR 55-60%, PF 1.5-2.0 ──
    if test_wr >= WR_YELLOW and test_pf >= PF_YELLOW:
        if hours_since >= RETRAIN_INTERVAL_HOURS and retrains_this_week < MAX_RETRAIN_PER_WEEK:
            result['action'] = 'RETRAIN'
            result['reason'] = f'time-based: {hours_since:.0f}h since last (WR {test_wr:.0%} PF {test_pf:.2f})'
            result['priority'] = 3
            return result
        else:
            result['action'] = 'SKIP'
            result['reason'] = f'stable: WR {test_wr:.0%} PF {test_pf:.2f} (next in {RETRAIN_INTERVAL_HOURS-hours_since:.0f}h)'
            result['priority'] = 4
            return result

    # ── Fallback ──
    result['action'] = 'SKIP'
    result['reason'] = f'default (WR {test_wr:.0%} PF {test_pf:.2f}, {test_nt} tr)'
    result['priority'] = 6
    return result


def decide_actions(status: dict) -> list:
    """
    Analyze ALL symbols, decide actions, return prioritized list
    of symbols to retrain (max MAX_RETRAIN_PER_CYCLE).
    """
    symbols_data = status.get('symbols', {})
    decisions = []
    for sym in SYMBOLS:
        quality = analyze_signal_quality(sym, symbols_data)
        decisions.append(quality)

    # Log all decisions
    for d in sorted(decisions, key=lambda x: x['priority']):
        icon = '🔴' if d['action'] == 'RETRAIN' else '🟢'
        log(f"{icon} {d['symbol']}: {d['action']} — {d['reason']}")

    # Return symbols to retrain (highest priority first)
    retrain = [d for d in decisions if d['action'] == 'RETRAIN']
    retrain.sort(key=lambda x: x['priority'])
    return retrain[:MAX_RETRAIN_PER_CYCLE]


def update_kelly_from_live_db():
    """Pull trade data from live DB and update Kelly sizing."""
    try:
        import sqlite3
        conn = sqlite3.connect(str(DB_PATH))
        cursor = conn.cursor()
        
        # Check if live_trades table exists
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='live_trades'")
        if not cursor.fetchone():
            log("No live_trades table yet", "WARN")
            conn.close()
            return None
        
        # Get all closed trades
        cursor.execute("""
            SELECT symbol, direction, entry_price, exit_price, entry_time, exit_time, pnl_net
            FROM live_trades
            WHERE exit_time IS NOT NULL AND pnl_net IS NOT NULL
            ORDER BY exit_time DESC
            LIMIT 500
        """)
        rows = cursor.fetchall()
        conn.close()
        
        if not rows:
            log("No closed trades in DB", "INFO")
            return None
        
        # Build per-symbol stats
        trades_by_symbol = {}
        for row in rows:
            sym, direction, entry_p, exit_p, entry_t, exit_t, pnl = row
            if sym not in trades_by_symbol:
                trades_by_symbol[sym] = []
            trades_by_symbol[sym].append({
                'pnl_net': float(pnl) if pnl else 0,
                'direction': direction,
            })
        
        # Update Kelly
        sizer = KellySizer()
        for sym, trades in trades_by_symbol.items():
            if len(trades) >= 30:
                stats = sizer.update_from_trades(sym, trades)
                log(f"Kelly {sym}: pos={stats.get('position_pct', 0)*100:.1f}% WR={stats.get('win_rate', 0)*100:.0f}% PF={stats.get('profit_factor', 0):.2f}")
            else:
                log(f"Kelly {sym}: insufficient trades ({len(trades)} < 30), skipping")
        
        return sizer.summary()
    
    except Exception as e:
        log(f"Kelly update failed: {e}", "ERROR")
        return None


def get_live_status() -> str:
    """Get current live trading status for report."""
    try:
        import sqlite3
        conn = sqlite3.connect(str(DB_PATH))
        cursor = conn.cursor()
        
        # Wallet balance
        cursor.execute("SELECT capital FROM live_capital ORDER BY timestamp DESC LIMIT 1")
        row = cursor.fetchone()
        balance = float(row[0]) if row else 0
        
        # Open positions
        cursor.execute("""
            SELECT symbol, position, entry_price, qty
            FROM live_state
            WHERE position != 0
        """)
        open_positions = cursor.fetchall()
        
        # Trades today
        cursor.execute("""
            SELECT COUNT(*), COALESCE(SUM(pnl_net), 0)
            FROM live_trades
            WHERE exit_time IS NOT NULL
              AND date(exit_time / 1000, 'unixepoch') = date('now')
        """)
        today_count, today_pnl = cursor.fetchone()
        
        conn.close()
        
        parts = [f"💰 **${balance:.2f}**"]
        if open_positions:
            pos_strs = []
            for sym, pos, entry, qty in open_positions:
                dir_symbol = "🟢"
                pnl_pct = 0  # no current_price available in DB
                pos_strs.append(f"{dir_symbol} {sym}")
            parts.append(f"📊 {' • '.join(pos_strs)}")
        else:
            parts.append("📊 No open positions")
        
        if today_count:
            parts.append(f"📈 Today: {today_count} trades | PnL ${float(today_pnl):.2f}")
        
        return " | ".join(parts)
    
    except Exception as e:
        return f"DB error: {e}"


def generate_report() -> str:
    """Generate condensed report for Telegram."""
    lines = []
    lines.append("📊 **Mimia Hourly Report**")
    lines.append("")
    
    # Live status
    live = get_live_status()
    lines.append(live)
    lines.append("")
    
    # Kelly summary
    try:
        sizer = KellySizer()
        kelly_data = sizer.data.get('symbols', {})
        if kelly_data:
            lines.append("**📐 Kelly Sizing**")
            for sym, k in sorted(kelly_data.items()):
                pp = k.get('position_pct', 0) * 100
                wr = k.get('win_rate', 0) * 100
                pf = k.get('profit_factor', 0)
                nt = k.get('n_trades', 0)
                if nt >= 30:
                    lines.append(f"  `{sym:<10}` {pp:.0f}%  WR{wr:.0f}%  PF{pf:.2f}  ({nt} tr)")
    except Exception as e:
        lines.append(f"Kelly: {e}")
    lines.append("")
    
    # Signal quality analysis
    status = get_retrain_status()
    symbols_data = status.get('symbols', {})
    lines.append("**🔍 Signal Quality**")
    lines.append(f"```")
    lines.append(f"{'SYMBOL':<10} {'LIVE-WR':>7} {'LIVE-PF':>7} {'BT-WR':>6} {'ACTION':<8} {'PRIO':>4}")
    lines.append(f"{'-'*10} {'-'*7} {'-'*7} {'-'*6} {'-'*8} {'-'*4}")
    for sym in SYMBOLS:
        quality = analyze_signal_quality(sym, symbols_data)
        n_display = quality['n_trades']
        lw = f"{quality['live_wr']:.0%}" if n_display >= MIN_TRADES_CURRENT_MODEL else f"~{quality['live_wr']:.0%}" if n_display > 0 else "N/A"
        lp = f"{quality['live_pf']:.2f}" if n_display >= MIN_TRADES_CURRENT_MODEL else "N/A"
        bw = f"{quality['bt_wr']:.0%}"
        act = quality['action']
        icon = "🔴" if act == "RETRAIN" else "🟢"
        prio = quality['priority']
        lines.append(f"{sym:<10} {lw:>7} {lp:>7} {bw:>6} {icon}{act:<6} {prio:>3}")
    lines.append(f"```")
    lines.append("")
    
    # Retrain status history
    if symbols_data:
        lines.append("**🔄 Retrain History**")
        for sym in sorted(symbols_data.keys()):
            s = symbols_data.get(sym, {})
            last = s.get('last_retrained', 'never')[:16] if s.get('last_retrained') else 'never'
            wr = s.get('wr', 0)
            pf = s.get('pf', 0)
            lines.append(f"  `{sym:<10}` WR{wr:.0f}% PF{pf:.2f} [{last}]")
    
    lines.append("")
    lines.append(f"🤖 _Mimia — {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC_")
    
    return '\n'.join(lines)


# ── Main ─────────────────────────────────────────────────────────────

def main():
    log("Hourly cycle starting")
    t0 = time.time()
    results = {'decisions': [], 'retrain': [], 'kelly': False, 'report': None}
    
    # ── Step 1: Analyze signal quality → decide actions ──────────
    status = get_retrain_status()
    decisions = decide_actions(status)
    results['decisions'] = decisions
    
    for d in decisions:
        sym = d['symbol']
        log(f"Retraining {sym} (priority {d['priority']}: {d['reason']})...")
        result = run_retrain(sym)
        results['retrain'].append({'symbol': sym, 'status': result.get('status'),
                                    'deployed': result.get('deployed', False)})
    
    # ── Step 2: Update Kelly ──────────────────────────────────────
    kelly_summary = update_kelly_from_live_db()
    results['kelly'] = kelly_summary is not None
    
    # ── Step 3: Generate report ───────────────────────────────────
    report = generate_report()
    results['report'] = report
    print(report)
    
    # ── Summary ───────────────────────────────────────────────────
    elapsed = time.time() - t0
    n_retrained = len(decisions)
    log(f"Cycle complete in {elapsed:.0f}s | Retrained: {n_retrained} | Kelly: {results['kelly']}")
    
    # Return report for Telegram delivery
    return report


def run_retrain(symbol: str) -> dict:
    """Run auto_retrain for one symbol and return result."""
    import subprocess
    try:
        result = subprocess.run(
            [sys.executable, str(RETRAIN_SCRIPT), '--symbol', symbol],
            capture_output=True, text=True, timeout=600,
            cwd=str(ROOT),  # = /root/projects/mimia-quant so auto_retrain's data/ paths resolve correctly
            env={**os.environ, 'PYTHONPATH': str(ROOT)}
        )
        if result.returncode == 0:
            log(f"Retrain {symbol} OK", "INFO")
            return {'status': 'ok', 'deployed': 'DEPLOYED' in result.stdout}
        else:
            log(f"Retrain {symbol} failed: {result.stderr[:200]}", "ERROR")
            return {'status': 'error', 'error': result.stderr[:200]}
    except subprocess.TimeoutExpired:
        log(f"Retrain {symbol} timed out", "ERROR")
        return {'status': 'timeout'}
    except Exception as e:
        log(f"Retrain {symbol} exception: {e}", "ERROR")
        return {'status': 'exception', 'error': str(e)}


if __name__ == '__main__':
    report = main()
    if report:
        # Write report to file for cron to pick up
        report_path = OUTPUT_DIR / f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        with open(report_path, 'w') as f:
            f.write(report)
        print(f"\nReport saved: {report_path}")
